### PR TITLE
Stop deleting package.json. Closes #10

### LINKED ISSUE #10: Some NPM packages need package.json to be present
Hi @nsams ,

I stumbled through a *minor* issue while using gulp with composer-extra-assets.

I'm used to the [gulp-load-plugins module](https://www.npmjs.com/package/gulp-load-plugins).
What this module does is essentially to automatically "require" gulp plugins based on the list of plugins listed in the **package.json** file.

Now, I'm sure you see the issue... composer-extra-assets is creating, then deleting the **package.json** file. Since there is no **package.json**, we cannot use [gulp-load-plugins module](https://www.npmjs.com/package/gulp-load-plugins) (or any other plugin that autoloads packages based on package.json).

Would you consider a pull-request that adds a `persist_package_json` parameter in the extra section that prevents the package.json file from being deleted?

```
{
  "extra": {
    "persist_package_json": true
  }
}
```

### PR DESCRIPTION
**Pull request by moufmouf**
Note: I'm allowing the user to modify `package.json` or `bower.json`. Only the `dependencies` section will be overwritten.

This can be useful sometimes. For instance, the [gulp-bower-files](https://www.npmjs.com/package/gulp-bower-files) extensions allows the use to put an extra section in "bower.json" that allows "gulp-bower-files" to ignore some packages. Therefore, it can be useful to let the possibility for the user to put additional material in those files.

On a side note, I added the "JSON_PRETTY_PRINT" tag to json_encode to get a pretty print. This is only supported in PHP 5.4. Hope this is not an issue for koala-framework. Let me know if it is.

### CODE REVIEW

**Comment by nsams** [comment]
looks good, thanks.

However please don't require php 5.4, instead use `if (defined('JSON_PRETTY_PRINT'))` - resulting in non-pretty JSON with php 5.3.

Or, you might even use the composer built in json formatter (they must have one, but I don't know if it is possible to use from a plugin)

**Comment by moufmouf** [comment]
Fixed. I used the `JsonFile` class from Composer to keeps compatibility with PHP 5.3.

**Comment by moufmouf** [comment]
After testing a bit more, I realize that the "package.json" files are generated for the root package but also for the packages in vendor/.
It makes no sense to generate "package.json" files in the vendor/ directory.
I adapted the PR to remove "package.json" from dependencies and keep it only for root package.

**Comment by nsams** [comment]
Makes sense.

Thanks for this PR :D

**Pull request merged**
